package com.jovij.OpenClinic.Model.DTO.Patient;

import com.jovij.OpenClinic.Model.DTO.Person.PersonResponseDTO;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;

public record PatientResponseDTO(
        UUID id,
        PersonResponseDTO person,
        @Schema(description = "Membership ID generated by the system (Format: OPCXXXXX)", example = "OPC00001")
        String membershipId
) {
}
